ej4: serv cli

serv: servidor.cpp Comm.h Connection.h Usuario.h ServidorBbs.h
	g++ -lpthread -Wall -o serv servidor.cpp

cli: cliente.cpp Comm.h Connection.h Usuario.h ServidorBbs.h
	g++ -lpthread -Wall -o cli cliente.cpp
