#! /bin/bash

# Nombre: generador-de-pass.sh
# Trabajo: Programacion en AWK
# Numero de ejercicio: 2
# Entrega: Primer Entrega
#
# Bevilaqcua Ricardo
# D`Aranno Facundo     34.842.320
# Marcela ....
# Moure Pablo          32.031.459
#
# comienzo del awk:

{
	#cierra la aplicacion en caso de que la longitud del pass sea inferior a lo establecido	
        
  	if ( length(pass) < longmin)
	{
              printf("\nERROR:\n\t la contraseña debe ser de una longitud minima de %d \n\n",longmin);
              exit 1
                
        }
}
